module.exports = script =>
  ` <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Commit Stats</title>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
      <style type="text/css">
        body {
          text-align: center;
          padding: 20px;
        }

        .section {
          margin: 20px auto;
        }

        a {
          text-decoration: none;
          color: rgb(54, 162, 235);
        }
      </style>
    </head>
    <body>
    <h2 id="repoName"></h2>
    <div class="section" style="width:40%">
      <P>commit count by author</P>
      <canvas id="author"></canvas>
    </div>
    <div class="section" style="width: 80%">
      <canvas id="day"></canvas>
    </div>
    <div class="section" style="width: 80%">
      <canvas id="week"></canvas>
    </div>
    <div class="section" style="width: 80%">
      <canvas id="month"></canvas>
    </div>
    <div class="section" style="width: 80%">
      <canvas id="year"></canvas>
    </div>
    <footer>Generated by <a href="https://github.com/sinchang/commit-stats">Commit Stats</a> at <span id="date"></span></footer>
    <script>
      ${script}
    </script>
    </body>
    </html>
  `
